String kAppName = 'iGetSporty Admin Panel';
const String kSideBarScreenRoute = "/side-bar-screen-route";
const String kDashboardScreenRoute = "/dashboard-screen-route";
const String kVenuesOwnerScreenRoute = "/venues-owner-screen-route";
const String kRevnueScreenRoute = "/revenue-screen-route";
const String kUsersScreenRoute = "/users-screen-route";
const String kBookingsScreenRoute = "/bookings-screen-route";
const String kUserDetailsScreenRoute = "/UserDetailsScreenRoute";
const String kBookingDetailsScreenRoute = "/BookingDetailsScreenRoute";
