import 'dart:ui';

const Color kPrimaryColor = Color(0xFFEE334E);
const Color kSecondaryColor = Color(0xFF00A651);
const Color kWhiteColor = Color(0xffFFFFFF);
const Color kWhiteShadeColor = Color(0xffFAFBFD);
const Color kBlackColor = Color(0xFF000000);
const Color kGreyColor = Color(0xFF858585);
const Color kSideBarTextColor = Color(0xFF1C1C1C);
const Color kPurpleColor = Color(0xFF6226EF);
const Color kPrimaryAccentColor = Color(0xFFEB5757);
const Color kStrokeColor = Color(0xFFCBCDCE);
const Color kBlackShadeColor = Color(0xFF202224);
const Color kGreyShadeColor = Color(0xFFF1F4F9);
const Color kGreyShad1Color = Color(0xFFD5D5D5);
const Color kGreyShade2Color = Color(0xFF979797);
const Color kGreyShade3Color = Color(0xFF2B3034);
const Color kGreenColor = Color(0xFF00B69B);
const Color kRedColor = Color(0xFFEF3826);
const Color kGreyShade4Color = Color(0xFFE5ECF6);
const Color kGreyShade5Color = Color(0xFFF7F9FB);
